[package]
name = "middleman-meta"
version = "1.0.0"
edition = "2018"
publish = false
authors = [ "yum0e",]

[dev-dependencies]

[dependencies.middleman]
path = ".."

[dependencies.elrond-wasm]
version = "0.29.3"

[dependencies.elrond-wasm-debug]
version = "0.29.3"
